"use client";

import { motion } from "framer-motion";
import { useState, useEffect } from "react";

export default function PlannerPreview() {
  // We'll animate showing the timeline one block at a time
  const [visibleBlocks, setVisibleBlocks] = useState(0);

  const blocks = [
    { time: "09:00", label: "Deep work: Finish proposal deck" },
    { time: "10:30", label: "Reply to priority emails (drafted for you)" },
    { time: "12:00", label: "Break + reset" },
    { time: "13:00", label: "Client call: Project sync" },
    { time: "14:00", label: "Prepare follow-up email (auto-generated)" },
    { time: "15:00", label: "Focus block: Marketing launch plan" },
  ];

  // Reveal each block one after another for a “being planned right now” feel
  useEffect(() => {
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setVisibleBlocks(i);
      if (i >= blocks.length) clearInterval(interval);
    }, 600); // new item every 0.6s
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="relative w-full py-24 px-6 md:px-10 flex flex-col items-center">
      <div className="w-full max-w-6xl grid lg:grid-cols-2 gap-12 items-start">
        {/* LEFT: Marketing copy */}
        <div className="flex flex-col">
          <div className="text-blue-600 font-semibold text-sm tracking-wide uppercase mb-3">
            Live demo
          </div>

          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight mb-6">
            FlowAI builds your day for you
          </h2>

          <p className="text-gray-600 text-base leading-relaxed mb-6 max-w-md">
            You tell FlowAI what needs to happen. It creates a realistic plan,
            protects your focus time, and even drafts the follow-ups you’ll need
            to send.
          </p>

          <ul className="text-sm text-gray-700 space-y-3">
            <li className="flex items-start gap-2">
              <span className="text-green-500">✓</span>
              <span>Smart time blocking based on how you actually work</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-green-500">✓</span>
              <span>Automatic email follow-ups built into your timeline</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-green-500">✓</span>
              <span>No “Sunday night planning” anymore</span>
            </li>
          </ul>
        </div>

        {/* RIGHT: Animated “your day” card */}
        <motion.div
          className="bg-white/70 backdrop-blur-xl border border-gray-200 rounded-2xl shadow-2xl p-6 w-full max-w-md mx-auto"
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.4 }}
        >
          <div className="flex items-start justify-between mb-4">
            <div>
              <div className="text-sm text-gray-500">Today</div>
              <div className="text-lg font-semibold text-gray-900">
                Your AI Schedule
              </div>
            </div>
            <div className="text-[11px] bg-blue-600 text-white font-semibold px-2 py-1 rounded-md shadow">
              Generated by FlowAI
            </div>
          </div>

          <ul className="space-y-3 text-sm text-gray-800">
            {blocks.slice(0, visibleBlocks).map((block, i) => (
              <motion.li
                key={i}
                className="flex gap-3 bg-gray-50 border border-gray-100 rounded-xl px-4 py-3 shadow-sm"
                initial={{ opacity: 0, y: 10, scale: 0.98 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                transition={{ duration: 0.3 }}
              >
                <span className="text-blue-600 font-semibold w-14 shrink-0">
                  {block.time}
                </span>
                <span className="leading-snug">{block.label}</span>
              </motion.li>
            ))}
          </ul>

          {visibleBlocks < blocks.length && (
            <div className="text-[11px] text-gray-500 text-center mt-4 italic">
              Planning your day…
            </div>
          )}
          {visibleBlocks === blocks.length && (
            <div className="text-[11px] text-green-600 text-center mt-4 font-medium">
              ✅ You’re planned. Stay in flow.
            </div>
          )}
        </motion.div>
      </div>
    </section>
  );
}
