"use client";

import { motion } from "framer-motion";

export default function PlannerPreviewCard() {
  return (
    <motion.div
      className="w-full max-w-sm rounded-xl border border-gray-200 bg-white/80 backdrop-blur-xl shadow-xl p-4 text-left"
      initial={{ y: 20, opacity: 0 }}
      whileInView={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.6 }}
    >
      <div className="text-xs text-gray-500 mb-2 flex items-center justify-between">
        <span>Today</span>
        <span className="text-[10px] text-blue-600 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded">
          Generated by Refraim AI
        </span>
      </div>

      <div className="text-sm font-medium text-gray-900 mb-3">
        Your AI Schedule
      </div>

      <div className="space-y-2 text-[13px]">
        {[
          { time: "09:00", task: "Deep work — Finish proposal", tag: "Focus" },
          { time: "10:30", task: "Reply to priority emails", tag: "Inbox" },
          { time: "13:00", task: "Client sync call", tag: "Meeting" },
          { time: "15:00", task: "Prep slides for tomorrow", tag: "Planning" },
        ].map((block, i) => (
          <motion.div
            key={i}
            className="flex items-start justify-between rounded-lg border border-gray-200 bg-gray-50 px-3 py-2"
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.15 * i }}
          >
            <div className="flex-1">
              <div className="text-blue-600 font-semibold tabular-nums text-[12px]">
                {block.time}
              </div>
              <div className="text-gray-800 leading-snug">{block.task}</div>
            </div>
            <div className="ml-3 text-[10px] bg-white border border-gray-300 rounded px-2 py-0.5 text-gray-600 whitespace-nowrap">
              {block.tag}
            </div>
          </motion.div>
        ))}
      </div>

      <div className="mt-4 text-[11px] text-gray-500 leading-snug border-t border-gray-200 pt-3">
        Refraim AI blocked <span className="text-blue-600 font-medium">2h</span> of
        protected focus time for you.
      </div>
    </motion.div>
  );
}
